---
version: '3'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: quay.io/debezium/kafka:2.2
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  postgres:
    # image: your_registry_namespace/postgis:15-master-decoderbufs
    image: quay.io/debezium/postgres:11-alpine
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=inventory

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    ports:
     - "9200:9200"
    environment:
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
     - xpack.security.enabled=false
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.10
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elastic
    ports:
      - 5601:5601

  connect:
    image: your_registry_namespace/connect-jdbc-es:2.2
    build:
      context: debezium-jdbc-es
      args:
        DEBEZIUM_VERSION: 2.2
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
