---
services:
  zookeeper:
    platform: linux/x86_64
    image: quay.io/debezium/zookeeper:3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    platform: linux/x86_64
    image: quay.io/debezium/kafka:3.2
    ports:
      - 9092:9092
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  mysql:
    platform: linux/x86_64
    image: quay.io/debezium/example-mysql:3.2
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw

  elastic:
    image: elasticsearch:7.17.16
    ports:
     - "9200:9200"
    environment:
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
     - xpack.security.enabled=false
     - "_JAVA_OPTIONS=-XX:UseSVE=0"

  kibana:
    container_name: kibana
    image: arm64v8/kibana:7.17.16
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elastic
    ports:
      - 5601:5601

  connect:
    image: your_registry_namespace/connect-jdbc-es:2.7
    build:
      context: docker
      args:
        DEBEZIUM_VERSION: 2.7
    ports:
     - 8083:8083
     - 5005:5005
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
     - JAVA_TOOL_OPTIONS="-XX:UseSVE=0"
