name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Kafka Connect-JDBC-Elasticsearch image
      run: cd debezium-jdbc-es && docker build . --tag your_registry_namespace/connect-jdbc-es:$(date +%s)
