name: Docker Image CI

on:
  push:
    branches: [ "main", "stacks" ]
  pull_request:
    branches: [ "main", "stacks" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the custom Opensearch Kafka Connect image
      run: cd mongodb-kafka-opensearch/containers/connect && docker build --build-arg DEBEZIUM_VERSION=3.2.2.Final --tag your_registry_namespace/my-connect-opensearch:$(date +%s) .
    - name: Build the custom Elastic Kafka Connect image (for mysql)
      run: cd mysql-kafka-elastic/docker && docker build --build-arg DEBEZIUM_VERSION=3.2.2.Final --tag your_registry_namespace/my-connect-elastic-mysql:$(date +%s) .
    - name: Build the custom Elastic Kafka Connect image (for postgres)
      run: cd postgres-kafka-elastic/docker && docker build --build-arg DEBEZIUM_VERSION=3.2.2.Final --tag your_registry_namespace/my-connect-elastic-pg:$(date +%s) .
